export * from './pages/BandaForm';
export * from './pages/CrearBandaUno';
export * from './pages/CrearBandaDos';
export * from './pages/CrearBandaTres';
export * from './pages/MisBandas';
export * from './pages/PerfilBanda';
export * from './pages/RedesSociales';   
export * from './modals/NuevasRedSocial';
export * from './pages/UpdateBandaForm';